### PR TITLE
Expose the semian identifier in AdapterExceptions

### PR DESCRIPTION
**Pull request by byroot**
@fw42 @Sirupsen for review please.

The idea is to be able to discriminate semian errors based on which resource fired it.

### CODE REVIEW

**Comment by Sirupsen** [comment]
LGTM

I'm assuming a follow up is fixing the case you described in #36?

**Comment by byroot** [comment]
Indeed. But for that It also requires to be able to identify the adapter native errors e.g. `Redis::BaseConnectionError`.

I'm not sure how I'll do it yet, but this pose the basics.

**Comment by Sirupsen** [comment]
K, sounds good.

**Comment by fw42** [comment]
:+1:

**Pull request merged**
