### PR TITLE
Change platform check to /linux/

### LINKED ISSUE #15: Platform check not sufficiently permissive
@Sirupsen @csfrancis I was trying to use semian on an x64 Ubuntu 14.10 installation and I got `Semian is not supported on x86_64-linux-gnu - all operations will no-op`

The current check is just `end_with?('-linux')` which clearly isn't sufficient, though I don't know enough about the format of `RUBY_PLATFORM` to say what else is needed.

### PR DESCRIPTION
**Pull request by csfrancis**
@Sirupsen, @eapache 

Fixes #15.

### CODE REVIEW

**Comment by eapache** [comment]
:+1:

**Comment by csfrancis** [comment]
Travis seems to be :sleeping:

**Comment by eapache** [comment]
I have noticed that on Sarama too - they must be very under-provisioned for free accounts

**Comment by Sirupsen** [comment]
We actually have a paid account, don't know how we can attach this to it @j-mutter ?

**Comment by j-mutter** [comment]
No, it's :hankey: - only private repos get access to our paid account :(

**Comment by csfrancis** [comment]
:poop:

**Comment by Sirupsen** [comment]
@joshk :(

**Comment by joshk** [comment]
what have I done?

**Comment by Sirupsen** [comment]
@joshk is it possible to attach public repositories to a paid account to get prioritized builds?

**Comment by joshk** [comment]
Not at the moment, we are working on that (merging .org and .com together)




That said, using the Docker setup means we have uber capacity. Any delays in builds today would be due to a queuing component failing which we recently fixed :)

**Comment by Sirupsen** [comment]
We're actually [on that](https://github.com/Shopify/semian/blob/master/.travis.yml#L3), you changed it at DockerCon :-)

**Comment by joshk** [comment]
Yep, I saw, thats why I was telling you about the downtime, because there should be no need for prioritised builds as we have ALLLL the capacity :)

**Pull request merged**
