### PR TITLE
Also rescue Errno::EINVAL in Redis adapter because of an upstream bug

### PR DESCRIPTION
**Pull request by byroot**
@Sirupsen @fw42 for review please.

Not sure if it's worth testing, it only appear after several reconnection attempts.

### CODE REVIEW

**Comment by Sirupsen** [comment]
How did you find this? Can we have a test case for it?

**Comment by byroot** [comment]
It appeared in Shopify's test suite, in a file where we test a lot of behaviour with all redises down in a row. That triggered that bug. I can try to add a repro in the test suite.

**Comment by byroot** [comment]
As discussed offline, it appear that big appear mostly on OS X. I tried to add a test for it but was unsuccessful.

I'll merge anyway and monitor the upstream ticket for resolution.

Ref: https://github.com/redis/hiredis-rb/issues/21

**Comment by fw42** [comment]
wow, this sucks

**Pull request merged**
